#!/usr/bin/env ruby
# coding: utf-8
# frozen_string_literal: true

$:.push("lib")
require "ezframe"
require "sequel"
require "table_manager"

include Ezframe

Config.init
DB.init
ColumnSets.init
TableManager.create_tables
