#!/usr/bin/env ruby
#coding: utf-8
require "ezframe"

include Ezframe
Config.init
DB.init
ColumnSets.init
dbinfo = DBInfo.new

ColumnSets.keys.each do |colset_key|
  column_set = ColumnSets[colset_key]
  dbinfo.check_diff(column_set)
end
